services:
  db:
    image: postgres:17
    container_name: rolkotech-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB?POSTGRES_DB variable not set}
      POSTGRES_USER: ${POSTGRES_USER?POSTGRES_USER variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?POSTGRES_PASSWORD variable not set}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5

  backend_prestart:
    image: '${DOCKER_IMAGE_BACKEND?DOCKER_IMAGE_BACKEND variable not set}-playwright:${TAG-latest}'
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rolkotech-backend-prestart-playwright
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    command: ["bash", "./scripts/create_test_data.sh"]

  backend:
    image: '${DOCKER_IMAGE_BACKEND?DOCKER_IMAGE_BACKEND variable not set}-playwright:${TAG-latest}'
    container_name: rolkotech-backend-playwright
    volumes:
      - ./backend:/app/backend
      - /app/backend/.venv
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
    ports:
      - "8000:8000"
    command: ["fastapi", "dev", "./app/main.py", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      db:
        condition: service_healthy
      backend_prestart:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/tags/"]
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 5
