services:
  db:
    image: postgres:17
    container_name: rolkotech-postgres
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB?POSTGRES_DB variable not set}
      POSTGRES_USER: ${POSTGRES_USER?POSTGRES_USER variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?POSTGRES_PASSWORD variable not set}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5

  backend_prestart:
    image: '${DOCKER_IMAGE_BACKEND?DOCKER_IMAGE_BACKEND variable not set}-dev:${TAG-latest}'
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rolkotech-backend-prestart
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    command: ["bash", "./scripts/prestart.sh"]

  backend:
    image: '${DOCKER_IMAGE_BACKEND?DOCKER_IMAGE_BACKEND variable not set}-dev:${TAG-latest}'
    container_name: rolkotech-backend
    volumes:
      - ./docker/coverage:/app/backend/coverage
      - ./backend:/app/backend
      - /app/backend/.venv
    env_file:
      - .env
    environment:
      POSTGRES_SERVER: db
    ports:
      - "8000:8000"
    command: ["fastapi", "dev", "./app/main.py", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      db:
        condition: service_healthy
      backend_prestart:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/tags/"]
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 5

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?DOCKER_IMAGE_FRONTEND variable not set}-dev:${TAG-latest}'
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev        
    container_name: rolkotech-frontend
    env_file:
      - .env
    environment:
      - BACKEND_HOST=${BACKEND_HOST?BACKEND_HOST variable not set}
      - API_VERSION_STR=${API_VERSION_STR?API_VERSION_STR variable not set}
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 5
