"""Keep comments if User is deleted

Revision ID: 0696179258eb
Revises: 1c739b75127d
Create Date: 2025-09-07 11:56:34.725444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0696179258eb'
down_revision: Union[str, None] = '1c739b75127d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
