"""Add featured column to BlogPost

Revision ID: 1c739b75127d
Revises: d52b115c9c30
Create Date: 2025-08-21 20:50:35.749639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c739b75127d'
down_revision: Union[str, None] = 'd52b115c9c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'featured')
    # ### end Alembic commands ###
