"""Add reply_to column to Comment

Revision ID: d52b115c9c30
Revises: 47604b49c840
Create Date: 2025-07-29 19:01:56.979619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52b115c9c30'
down_revision: Union[str, None] = '47604b49c840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('reply_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['reply_to'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'reply_to')
    # ### end Alembic commands ###
