"""Updates 1

Revision ID: d65bccdde946
Revises: 53f1bc34cf10
Create Date: 2025-05-03 15:32:53.144474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd65bccdde946'
down_revision: Union[str, None] = '53f1bc34cf10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_unique_constraint(None, 'blogpost', ['url'])
    op.add_column('blogposttaglink', sa.Column('blog_post_id', sa.Integer(), nullable=False))
    op.drop_constraint('blogposttaglink_post_id_fkey', 'blogposttaglink', type_='foreignkey')
    op.create_foreign_key(None, 'blogposttaglink', 'blogpost', ['blog_post_id'], ['id'])
    op.drop_column('blogposttaglink', 'post_id')
    op.add_column('comment', sa.Column('comment_date', sa.DateTime(), nullable=False))
    op.add_column('comment', sa.Column('blog_post_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_user_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_post_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'blogpost', ['blog_post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'creation_date')
    op.drop_column('comment', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_post_id_fkey', 'comment', 'blogpost', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('comment_user_id_fkey', 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('comment', 'blog_post_id')
    op.drop_column('comment', 'comment_date')
    op.add_column('blogposttaglink', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blogposttaglink', type_='foreignkey')
    op.create_foreign_key('blogposttaglink_post_id_fkey', 'blogposttaglink', 'blogpost', ['post_id'], ['id'])
    op.drop_column('blogposttaglink', 'blog_post_id')
    op.drop_constraint(None, 'blogpost', type_='unique')
    op.drop_column('blogpost', 'url')
    # ### end Alembic commands ###
