name: Lint Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/lint_frontend.yml"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "frontend/**"
      - ".github/workflows/lint_frontend.yml"

jobs:
  lint_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22.16.0"
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run linting check
        run: scripts/lint.sh
        working-directory: frontend
