name: Lint Backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "backend/app/**"
      - "backend/scripts/lint.sh"
      - "backend/pyproject.toml"
      - ".github/workflows/lint_backend.yml"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "backend/app/**"
      - "backend/scripts/lint.sh"
      - "backend/pyproject.toml"
      - ".github/workflows/lint_backend.yml"

jobs:
  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --group dev
        working-directory: backend

      - name: Run linting
        run: uv run bash scripts/lint.sh
        working-directory: backend
